# -*- coding: utf-8 -*-
"""Mortalidad y morbilidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbF2-cT7fUyv0q33jVhOIzZZAPZLdmWO
"""



import pandas as pd

# Ruta del archivo Excel
file_path = '/content/Indicadores_mortalidad_y_morbilidad_según_departamento,_municipio_y_año_20251223.xlsx'

# Cargar el archivo Excel en un DataFrame de pandas
df = pd.read_excel(file_path)

# Asegurar que los códigos sean texto
df["CodDepartamento"] = df["CodDepartamento"].astype(int).astype(str).str.zfill(2)
df["CodMunicipio"] = df["CodMunicipio"].astype(int).astype(str).str.zfill(5)


# Mostrar las primeras 5 filas del DataFrame
display(df.head())



"""### Eliminación de valores nulos

Como se identificó que las columnas 'Indicador' y 'Año' tienen un número muy pequeño de valores nulos, procederemos a eliminar las filas completas que contengan al menos un valor nulo. Esto nos ayudará a tener un dataset más limpio para el análisis posterior.
"""

df_cleaned = df.dropna()

print(f"Dimensiones del DataFrame original: {df.shape}")
print(f"Dimensiones del DataFrame después de eliminar nulos: {df_cleaned.shape}")

display(df_cleaned.isnull().sum())

"""### Información general del DataFrame

Primero, veamos un resumen de la información del DataFrame, incluyendo los tipos de datos de cada columna y la cantidad de valores no nulos. Esto nos ayudará a identificar posibles problemas con los tipos de datos o valores faltantes.
"""

display(df.info())

"""### Estadísticas descriptivas

A continuación, generaremos estadísticas descriptivas para las columnas numéricas. Esto nos dará una idea de la distribución de los datos, como la media, la desviación estándar, los valores mínimos y máximos, y los cuartiles.
"""

display(df.describe())

"""### Conteo de valores nulos por columna

Finalmente, vamos a contar cuántos valores nulos hay en cada columna para entender mejor la completitud del dataset.
"""

display(df.isnull().sum())



"""# Task
Perform data type adjustment by converting the 'Año' column from float to integer. Analyze and visualize the distribution of 'Valor Indicador' using a histogram and count unique values in the 'Indicador' column. Analyze and visualize temporal trends of 'Valor Indicador' by calculating the average per 'Año' and plotting a line graph with an appropriate legend. Finally, summarize the data cleaning adjustments and key findings from the visualizations.

## Ajuste de tipos de datos

### Subtask:
Convertir la columna 'Año' de tipo flotante a entero, ya que representa años y es más adecuado para el análisis temporal.

**Reasoning**:
The subtask requires converting the 'Año' column to an integer type. Since `df_cleaned` was created by dropping nulls, the 'Año' column should not contain NaN values, allowing for a direct conversion to integer. I will convert the column and then verify the data type.
"""

df_cleaned['Año'] = df_cleaned['Año'].astype(int)
display(df_cleaned['Año'].dtype)

"""**Reasoning**:
The previous code produced a `SettingWithCopyWarning` when attempting to convert the 'Año' column to an integer. To avoid this warning and ensure the operation is performed on the original DataFrame, I will use `.loc` for explicit assignment.


"""

df_cleaned.loc[:, 'Año'] = df_cleaned['Año'].astype(int)
display(df_cleaned['Año'].dtype)

"""## Análisis y Visualización de la Distribución del Indicador

### Subtask:
Generar un histograma para la columna 'Valor Indicador' para observar su distribución. Adicionalmente, se realizará un conteo de los valores únicos en la columna 'Indicador' para comprender la diversidad de indicadores presentes.

**Reasoning**:
First, I will import the necessary libraries, `matplotlib.pyplot` and `seaborn`, to create visualizations. Then, I will generate a histogram of the 'Valor Indicador' column to visualize its distribution, add appropriate labels, and display the plot. Finally, I will count and print the number of unique values in the 'Indicador' column to understand the diversity of indicators.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Crear un histograma para la columna 'Valor Indicador'
plt.figure(figsize=(10, 6))
sns.histplot(df_cleaned['Valor Indicador'], kde=True)
plt.title('Distribución del Valor del Indicador')
plt.xlabel('Valor del Indicador')
plt.ylabel('Frecuencia')
plt.show()

# Contar los valores únicos en la columna 'Indicador'
unique_indicators_count = df_cleaned['Indicador'].nunique()
print(f"Número de indicadores únicos: {unique_indicators_count}")

"""## Análisis y Visualización de Tendencias Temporales

### Subtask:
Visualizar la tendencia del 'Valor Indicador' a lo largo de los años. Esto implicará calcular el promedio del 'Valor Indicador' por 'Año' y representarlo en un gráfico de líneas para identificar patrones temporales. Se incluirá una leyenda apropiada.

**Reasoning**:
To visualize the temporal trend of 'Valor Indicador', I will first group the `df_cleaned` DataFrame by 'Año' and calculate the mean of 'Valor Indicador' for each year. Then, I will create a line plot using this aggregated data to display the trend over time, adding a title and appropriate axis labels.
"""

yearly_average_indicator = df_cleaned.groupby('Año')['Valor Indicador'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x='Año', y='Valor Indicador', data=yearly_average_indicator, marker='o')
plt.title('Tendencia Temporal del Valor Indicador Promedio')
plt.xlabel('Año')
plt.ylabel('Valor Indicador Promedio')
plt.grid(True)
plt.show()

"""## Finalizar tarea

### Subtask:
Resumir los ajustes de limpieza realizados y los principales hallazgos de las visualizaciones generadas.

## Summary:

### Q&A
*   **What data cleaning adjustments were performed?**
    The 'Año' column was converted from a float data type to an integer (`int64`).
*   **What are the key findings from the generated visualizations?**
    The 'Valor Indicador' distribution was visualized, and the count of unique indicators was determined to be 30. A line graph showed the temporal trend of the average 'Valor Indicador' over the years.

### Data Analysis Key Findings
*   The 'Año' column was successfully converted from a float to an integer (`int64`), which is more appropriate for representing years in temporal analysis.
*   There are 30 unique indicators present in the dataset.
*   A histogram was generated to visualize the distribution of 'Valor Indicador', showing its frequency across different values.
*   A clear temporal trend of the average 'Valor Indicador' was identified, showing how this value changes over the years based on the line plot.

### Insights or Next Steps
*   The diverse range of 30 unique indicators suggests a comprehensive dataset that could be further analyzed by segmenting the temporal trends for specific indicators to identify which ones drive the overall average trends.
*   Further investigation into the distribution of 'Valor Indicador' could involve identifying outliers or specific ranges that are most common, potentially leading to targeted analyses for those values.
"""



"""### Verificación final de valores nulos y duplicados

Antes de cualquier exportación, es crucial realizar una última verificación para asegurar la ausencia de valores nulos y la presencia de filas duplicadas en el DataFrame `df_cleaned`.
"""

print("Conteo de valores nulos en df_cleaned:")
display(df_cleaned.isnull().sum())

print("\nNúmero de filas duplicadas en df_cleaned:")
duplicated_rows_count = df_cleaned.duplicated().sum()
print(f"Hay {duplicated_rows_count} filas duplicadas.")

if duplicated_rows_count > 0:
    print("\nMostrando las primeras 5 filas duplicadas:")
    display(df_cleaned[df_cleaned.duplicated(keep=False)].head())



"""### Conversión de tipos de datos para 'CodDepartamento' y 'CodMunicipio'

Para preparar el DataFrame para la exportación, se convertirán las columnas 'CodDepartamento' y 'CodMunicipio' a tipo texto (string). Esto es útil para asegurar que estos códigos se traten como identificadores y no como valores numéricos sobre los cuales se puedan realizar operaciones matemáticas.
"""

df_cleaned.loc[:, 'CodDepartamento'] = df_cleaned['CodDepartamento'].astype(str)
df_cleaned.loc[:, 'CodMunicipio'] = df_cleaned['CodMunicipio'].astype(str)

print("Nuevos tipos de datos para 'CodDepartamento' y 'CodMunicipio':")
display(df_cleaned[['CodDepartamento', 'CodMunicipio']].dtypes)



"""### Exportar DataFrame a archivo Excel

Finalmente, exportaremos el DataFrame `df_cleaned` a un archivo Excel (`.xlsx`). Esto guardará todos los datos procesados y limpios en un formato fácilmente accesible para futuros análisis o reportes. Se evitará exportar el índice del DataFrame.
"""

output_file_path = '/content/datos_limpios_mortalidad_morbilidad.xlsx'
df_cleaned.to_excel(output_file_path, index=False)

print(f"El DataFrame limpio ha sido exportado exitosamente a: {output_file_path}")