# -*- coding: utf-8 -*-
"""Proyecciones_Población.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGhi9-2WqWCOJ40kynjzXDupXJjzclm0

### Importación de Librerías

Primero, importaremos las librerías necesarias para la manipulación y visualización de datos. `pandas` es fundamental para trabajar con DataFrames, `numpy` para operaciones numéricas y `matplotlib.pyplot` y `seaborn` para gráficos.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Librerías importadas exitosamente.")



"""### Carga del Dataset y Conversión de Columnas

Cargaremos el archivo `Proyecciones de población.xlsx` en un DataFrame de pandas. Luego, para asegurar la correcta manipulación de los identificadores geográficos, convertiremos las columnas 'DP' (Departamento) y 'MPIO' (Municipio) a tipo de dato `string`.
"""



df_poblacion = pd.read_excel('Proyecciones de población.xlsx')

# Asegurar que los códigos sean texto
df_poblacion["DP"] = df_poblacion["DP"].astype(int).astype(str).str.zfill(2)
df_poblacion["MPIO"] = df_poblacion["MPIO"].astype(int).astype(str).str.zfill(5)

print("Primeras 5 filas del dataset:")
display(df_poblacion.head())
print("\nDataset cargado correctamente en DataFrame df_poblacion")

"""### Exploración Inicial del Dataset

Comenzaremos con una exploración inicial para comprender la estructura básica del DataFrame `df_poblacion`. Esto incluye:

1.  **Dimensiones del DataFrame**: Número de filas y columnas.
2.  **Tipos de Datos**: Identificar el tipo de datos de cada columna.
3.  **Valores Nulos**: Verificar la presencia y cantidad de valores nulos en cada columna.
"""

print('Dimensiones del DataFrame (filas, columnas):', df_poblacion.shape)
print('\nInformación general del DataFrame (tipos de datos y valores no nulos):')
display(df_poblacion.info())
print('\nConteo de valores nulos por columna:')
display(df_poblacion.isnull().sum())

"""- Tipos de Datos Consistentes: Las columnas DP, DPNOM, MPIO, DPMP y ÁREA GEOGRÁFICA son de tipo object (cadena de texto), lo cual es adecuado para datos categóricos y geográficos. Las columnas AÑO y Población son de tipo int64, apropiadas para valores numéricos.

-  según la exploración inicial, no se encontraron valores nulos en ninguna de las columnas del DataFrame df_poblacion. Todos los conteos de isnull().sum() resultaron en cero para cada columna, lo que indica que el dataset está completo en este aspecto
"""



"""### Exploración de Valores Únicos y Rangos de Columnas Clave

Procederemos a examinar los valores únicos de las columnas categóricas para entender la diversidad de los departamentos y áreas geográficas, y los rangos de las columnas numéricas para observar la extensión de los años y la población.
"""

print('Valores únicos en la columna AÑO:', sorted(df_poblacion['AÑO'].unique()))
print('\nNúmero de valores únicos en la columna DPNOM (Departamento):', df_poblacion['DPNOM'].nunique())
print('Primeros 10 valores únicos en la columna DPNOM:', df_poblacion['DPNOM'].unique()[:10])
print('\nNúmero de valores únicos en la columna ÁREA GEOGRÁFICA:', df_poblacion['ÁREA GEOGRÁFICA'].nunique())
print('Valores únicos en la columna ÁREA GEOGRÁFICA:', df_poblacion['ÁREA GEOGRÁFICA'].unique())

"""Ahora, examinemos las estadísticas descriptivas de la columna 'Población' para entender su distribución."""

print('\nEstadísticas descriptivas de la columna Población:')
display(df_poblacion['Población'].describe())

"""### Visualización de la Población Total por Año

Para entender la tendencia general de la población a lo largo del tiempo, crearemos un gráfico de líneas que muestre la población total proyectada para cada año. Primero, agruparemos los datos por 'AÑO' y sumaremos la 'Población' para obtener el total anual.
"""

poblacion_por_año = df_poblacion.groupby('AÑO')['Población'].sum().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=poblacion_por_año, x='AÑO', y='Población', marker='o')
plt.title('Población Total Proyectada por Año')
plt.xlabel('Año')
plt.ylabel('Población Total')
plt.grid(True)
plt.xticks(poblacion_por_año['AÑO'], rotation=45)
plt.tight_layout()
plt.show()

print("Gráfico de población total por año generado exitosamente.")



"""### Renombramiento de Columnas

Renombramos las columnas existentes del DataFrame `df_poblacion` para mejorar su claridad y consistencia. Esto facilitará futuras operaciones y análisis de los datos.
"""

df_poblacion = df_poblacion.rename(columns={
    'DP': 'CodDepartamento',
    'DPNOM': 'Departamento',
    'MPIO': 'CodMunicipio',
    'DPMP': 'Municipio',
    'AÑO': 'Año',
    'ÁREA GEOGRÁFICA': 'AreaGeografica',
    'Población': 'Poblacion'
})

print("Columnas renombradas exitosamente. Las nuevas columnas son:")
display(df_poblacion.columns.tolist())
print("Primeras 5 filas del dataset con las columnas renombradas:")
display(df_poblacion.head())

"""Se ha importado las librerías esenciales (pandas, numpy, matplotlib.pyplot, seaborn), cargado el archivo Proyecciones de población.xlsx en un DataFrame llamado df_poblacion, asegurando que las columnas DP y MPIO se manejen como cadenas de texto con ceros iniciales. Realice una exploración inicial donde confirmamos que el DataFrame tiene 53,856 filas y 7 columnas, los tipos de datos son adecuados para cada columna y, muy importante, no existen valores nulos. Posteriormente, exploramos los valores únicos y rangos de las columnas clave como AÑO, DPNOM y ÁREA GEOGRÁFICA, y analizamos las estadísticas descriptivas de la Población, revelando un rango de años de 2020 a 2035 y una alta variabilidad en los tamaños de población. Finalmente, renombramos columnas para mejorar la claridad, cambiando 'DP' a 'CodDepartamento', 'DPNOM' a 'Departamento', 'MPIO' a 'CodMunicipio', 'DPMP' a 'Municipio', 'ÁREA GEOGRÁFICA' a 'AreaGeografica' y 'Población' a 'Poblacion' (y 'AÑO' a 'Año').

Una vez realizada la limpieza se procede a exportar en formato xlsx para integrarlo en power bi.
"""



"""### Exportación del DataFrame a Formato XLSX

Exportaremos el DataFrame `df_poblacion` a un archivo de Excel (`.xlsx`) para su uso posterior, por ejemplo, en herramientas de visualización como Power BI. El archivo se guardará con el nombre `proyecciones_poblacion_limpio.xlsx`.
"""

output_file_name = 'proyecciones_poblacion_limpio.xlsx'
df_poblacion.to_excel(output_file_name, index=False)

print(f"DataFrame exportado exitosamente a '{output_file_name}'")