# -*- coding: utf-8 -*-
"""Registro discapacidad RLCPD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNZk9VGUvOC4dJ0r5aCjcTUumQmjMmuy
"""

#Importación de librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Carga de Dataset

file_path = '/content/Registro_para_la_Localización_y_Caracterización_de_personas_con_Discapacidad_-_RLCPD_20251222.xlsx'
df = pd.read_excel(file_path)
display(df.head())
print( )

#Tipos de datos y valores nulos

df.info()



"""# Task
Perform an exploratory data analysis (EDA) on the `df` DataFrame. This EDA should include:
1.  **Quantifying Null Values**: Identify and count null values for each column.
2.  **Descriptive Statistics**: Generate descriptive statistics (mean, median, standard deviation, etc.) for the 'NumPersonas' column.
3.  **Frequency Analysis for 'DepartamentoRegistro'**: Count the unique values in 'DepartamentoRegistro', display their frequencies, and visualize the top departments using a bar chart.
4.  **Frequency Analysis for 'TipoAlteracion'**: Count the unique values in 'TipoAlteracion', display their frequencies, and visualize the most common types of alterations using a bar chart.
5.  **Temporal Analysis for 'FechaRegistro'**: Determine the minimum and maximum dates in 'FechaRegistro' and visualize the distribution of records over time (e.g., by year or month) to identify temporal trends.
6.  **Combined Visualizations**: Create visualizations to explore relationships between 'DepartamentoRegistro' and 'NumPersonas', or 'TipoAlteracion' over time, ensuring clear legends.
7.  **Summary of Findings**: Summarize the key insights from the EDA, providing justifications for each observation, and highlighting any significant patterns, anomalies, or relevant information for future research.

## Verificar Valores Nulos

### Subtask:
Verificar y cuantificar los valores nulos en cada columna del DataFrame `df` para entender la completitud de los datos.

**Reasoning**:
To verify and quantify null values in each column, I will use the `.isnull()` method followed by `.sum()` on the DataFrame `df`.
"""

df.isnull().sum()

"""## Estadísticas Descriptivas para NumPersonas

### Subtask:
Generar estadísticas descriptivas (media, mediana, desviación estándar, etc.) para la columna numérica 'NumPersonas' para entender su distribución y variabilidad.

**Reasoning**:
To generate descriptive statistics for the 'NumPersonas' column, I will use the `.describe()` method on that specific column of the DataFrame `df`.
"""

df['NumPersonas'].describe()

"""## Análisis de DepartamentoRegistro

### Subtask:
Contar y mostrar la frecuencia de los valores únicos en la columna 'DepartamentoRegistro'. Visualizar los departamentos con más registros en un gráfico de barras para identificar las regiones con mayor número de casos.

**Reasoning**:
To analyze the frequency of 'DepartamentoRegistro', I will first calculate the value counts for this column to get the frequency of each unique department. Then, I will select the top 15 departments for visualization.
"""

df_cleaned = df[df['DepartamentoRegistro'] != 'ERROR: #NAME?']
department_counts = df_cleaned['DepartamentoRegistro'].value_counts()
top_departments = department_counts.head(15)
print("Frecuencia de valores únicos en 'DepartamentoRegistro':")
print(department_counts)
print("\nTop 15 Departamentos por Número de Registros:")
print(top_departments)

"""**Reasoning**:
Now that the top departments have been identified, I will create a bar chart to visualize their frequencies. This will provide a clear representation of the departments with the most records, with appropriate labels and title for readability.


"""

plt.figure(figsize=(12, 6))
sns.barplot(x=top_departments.index, y=top_departments.values, palette='viridis')
plt.title('Top 15 Departamentos por Número de Registros')
plt.xlabel('Departamento')
plt.ylabel('Número de Registros')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""**Reasoning**:
To address the `FutureWarning` from `seaborn` regarding the `palette` argument, I will explicitly set `hue` to the x-axis variable and `legend` to `False` in the `sns.barplot` call.


"""

plt.figure(figsize=(12, 6))
sns.barplot(x=top_departments.index, y=top_departments.values, hue=top_departments.index, palette='viridis', legend=False)
plt.title('Top 15 Departamentos por Número de Registros')
plt.xlabel('Departamento')
plt.ylabel('Número de Registros')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Análisis de TipoAlteracion

### Subtask:
Contar y mostrar la frecuencia de los valores únicos en la columna 'TipoAlteracion'. Visualizar los tipos de alteración más comunes en un gráfico de barras para entender la distribución de las discapacidades.

**Reasoning**:
To analyze the frequency of 'TipoAlteracion', I will calculate the value counts for this column to get the frequency of each unique alteration type. Then, I will select the top 10 alteration types for visualization.
"""

alteration_counts = df['TipoAlteracion'].value_counts()
top_alterations = alteration_counts.head(10)
print("Frecuencia de valores únicos en 'TipoAlteracion':")
print(alteration_counts)
print("\nTop 10 Tipos de Alteración por Número de Registros:")
print(top_alterations)

"""**Reasoning**:
Now that the top alteration types have been identified, I will create a bar chart to visualize their frequencies. This will provide a clear representation of the most common alteration types, with appropriate labels and title for readability and addressing any seaborn warnings.


"""

plt.figure(figsize=(14, 7))
sns.barplot(x=top_alterations.index, y=top_alterations.values, hue=top_alterations.index, palette='viridis', legend=False)
plt.title('Top 10 Tipos de Alteración por Número de Registros')
plt.xlabel('Tipo de Alteración')
plt.ylabel('Número de Registros')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Análisis Temporal para FechaRegistro

### Subtask:
Determinar la fecha mínima y máxima en la columna 'FechaRegistro' y visualizar la distribución de registros a lo largo del tiempo (por ejemplo, por año o mes) para identificar tendencias temporales.

## Análisis Temporal para FechaRegistro

### Subtask:
Determinar la fecha mínima y máxima en la columna 'FechaRegistro' y visualizar la distribución de registros a lo largo del tiempo (por ejemplo, por año o mes) para identificar tendencias temporales.

**Reasoning**:
To determine the time span of the data, I will extract and print the minimum and maximum dates from the 'FechaRegistro' column.
"""

min_date = df['FechaRegistro'].min()
max_date = df['FechaRegistro'].max()

print(f"Fecha Mínima: {min_date}")
print(f"Fecha Máxima: {max_date}")

"""**Reasoning**:
To visualize the distribution of records over time and identify temporal trends, I will extract the year from the 'FechaRegistro' column, count the occurrences of each year, and then create a line plot to display these yearly counts.


"""

df['Year'] = df['FechaRegistro'].dt.year
year_counts = df['Year'].value_counts().sort_index()

plt.figure(figsize=(12, 6))
sns.lineplot(x=year_counts.index, y=year_counts.values, marker='o')
plt.title('Número de Registros por Año')
plt.xlabel('Año')
plt.ylabel('Número de Registros')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## Combined Visualizations: DepartamentoRegistro vs NumPersonas

### Subtask:
Create a visualization to explore the relationship between 'DepartamentoRegistro' and 'NumPersonas' by aggregating the number of people per department.

**Reasoning**:
To explore the relationship between 'DepartamentoRegistro' and 'NumPersonas', I will first group the DataFrame by 'DepartamentoRegistro' and sum the 'NumPersonas' for each department. Then, I will sort the results to identify the departments with the highest number of registered people.
"""

department_num_personas = df.groupby('DepartamentoRegistro')['NumPersonas'].sum().sort_values(ascending=False)
top_10_departments_num_personas = department_num_personas.head(10)

print("Top 10 Departamentos por Número Total de Personas:")
print(top_10_departments_num_personas)

"""**Reasoning**:
Now that the top departments by total number of people have been identified, I will create a bar chart to visualize this relationship, ensuring appropriate labels, title, and rotated x-axis labels for readability.


"""

plt.figure(figsize=(14, 7))
sns.barplot(x=top_10_departments_num_personas.index, y=top_10_departments_num_personas.values, hue=top_10_departments_num_personas.index, palette='viridis', legend=False)
plt.title('Top 10 Departamentos por Número Total de Personas Registradas')
plt.xlabel('Departamento')
plt.ylabel('Número Total de Personas')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Visualización Combinada de Datos: TipoAlteracion a lo largo del tiempo

### Subtask:
Visualize the distribution of 'TipoAlteracion' over time (e.g., by year) to identify temporal trends in different types of alterations.

**Reasoning**:
To visualize the temporal trends of 'TipoAlteracion', I will first group the DataFrame by 'Year' and 'TipoAlteracion' and count the occurrences. This will provide the data necessary to plot the distribution of each alteration type over the years.
"""

alteration_yearly_counts = df.groupby(['Year', 'TipoAlteracion']).size().reset_index(name='Count')
print("Recuentos anuales de cada TipoAlteracion:")
print(alteration_yearly_counts.head())

"""**Reasoning**:
To make the temporal visualization manageable and insightful, I will filter the `alteration_yearly_counts` DataFrame to include only the top 10 most frequent 'TipoAlteracion' types, which were identified in a previous step.


"""

top_10_alteration_types = top_alterations.index.tolist()
alteration_yearly_counts_filtered = alteration_yearly_counts[alteration_yearly_counts['TipoAlteracion'].isin(top_10_alteration_types)]

print("Recuentos anuales filtrados para los 10 principales tipos de alteración:")
print(alteration_yearly_counts_filtered.head())

"""**Reasoning**:
Now that the yearly counts for the top alteration types are filtered, I will create a line plot to visualize their temporal trends. This will allow us to observe how the frequency of each alteration type has changed over the years, using different colors for each type and including a legend for clarity.


"""

plt.figure(figsize=(15, 8))
sns.lineplot(data=alteration_yearly_counts_filtered, x='Year', y='Count', hue='TipoAlteracion', marker='o')
plt.title('Distribución Temporal de los Principales Tipos de Alteración')
plt.xlabel('Año')
plt.ylabel('Número de Registros')
plt.grid(True)
plt.xticks(rotation=45)
plt.legend(title='Tipo de Alteración', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""## Eliminar Códigos de 'DepartamentoRegistro' y 'MunicipioRegistro'

### Subtask:
Eliminar los códigos numéricos y el guion que los precede de las columnas `DepartamentoRegistro` y `MunicipioRegistro`, dejando solo el nombre del departamento o municipio.

**Reasoning**:
Para eliminar los códigos de las columnas `DepartamentoRegistro` y `MunicipioRegistro`, se utilizará el método `str.split(' - ', 1).str[1]` para dividir la cadena por el primer ' - ' y tomar la segunda parte, que corresponde solo al nombre. Esto se aplicará a ambas columnas.

## Verificar la Presencia de Columnas de Código

### Subtask:
Confirmar que las columnas `CodDepartamento` y `CodMunicipio` todavía existen en el DataFrame después de las operaciones anteriores.

**Reasoning**:
Para verificar la existencia de las columnas `CodDepartamento` y `CodMunicipio`, simplemente mostraré todas las columnas del DataFrame `df`.
"""

print(df.columns)

import re
import numpy as np
import pandas as pd

# Function to remove the code prefix from a string
def remove_code_prefix(text):
    if pd.isna(text):
        return np.nan
    text = str(text) # Ensure the value is a string
    match = re.match(r'^\d+\s*-\s*(.*)', text)
    if match:
        return match.group(1).strip()
    return text.strip() # Return original text if pattern not found, stripping whitespace

# Apply the function to DepartamentoRegistro and MunicipioRegistro columns
df['DepartamentoRegistro'] = df['DepartamentoRegistro'].apply(remove_code_prefix)
df['MunicipioRegistro'] = df['MunicipioRegistro'].apply(remove_code_prefix)

display(df[['DepartamentoRegistro', 'MunicipioRegistro']].head())

"""## Summary:

### Data Analysis Key Findings

*   **Null Values**: The dataset is complete, with no missing values identified across any of the columns (`DepartamentoRegistro`, `MunicipioRegistro`, `FechaRegistro`, `TipoAlteracion`, `NumPersonas`).
*   **Descriptive Statistics for 'NumPersonas'**: The `NumPersonas` column has 576,308 entries, with an average of approximately 3.46 persons per record. The median is 2.00, suggesting a right-skewed distribution, and the maximum value is 476, indicating a wide range and potential outliers.
*   **Frequency Analysis for 'DepartamentoRegistro'**:
    *   '05 - Antioquia' has the highest number of records (74,644), followed by '76 - Valle del Cauca' (38,298) and '25 - Cundinamarca' (36,581).
    *   A notable data quality issue was identified with 'ERROR: #NAME?' appearing in 6,532 records.
*   **Frequency Analysis for 'TipoAlteracion'**: The most common type of alteration is "El movimiento del cuerpo, manos, brazos, piernas" with 171,472 records, followed by "El sistema nervioso" (139,727 records) and "Los ojos" (78,903 records).
*   **Temporal Analysis for 'FechaRegistro'**: The records span from `2002-01-13` to `2020-08-05`, covering an 18-year period. The distribution of records over time shows yearly trends.
*   **Combined Analysis: 'DepartamentoRegistro' vs. 'NumPersonas'**: When aggregating the total number of people, 'Bogotá, D.C.' leads with 323,262 people, followed by 'Antioquia' (275,297 people) and 'Valle del Cauca' (156,261 people). This differs from the department count for records, indicating varying numbers of people per record across departments.
*   **Combined Analysis: 'TipoAlteracion' over Time**: Visualizations showed how the frequency of the top alteration types has evolved annually, highlighting temporal trends for each specific type of alteration.

### Insights or Next Steps

*   **Data Quality Improvement**: Investigate and rectify the 'ERROR: #NAME?' values in the 'DepartamentoRegistro' column to ensure data integrity and accuracy in regional analysis.
*   **Outlier Investigation**: Further investigate the 'NumPersonas' column, specifically the records with very high values (e.g., 476), to determine if they represent legitimate large groups or potential data entry errors.
*   **Deep Dive into Temporal Trends**: Analyze specific years where significant changes in 'TipoAlteracion' counts or overall record volumes are observed to understand the underlying causes (e.g., policy changes, reporting initiatives, or major events).

# Task
Create new columns `CodDepartamento` and `CodMunicipio` in the `df` DataFrame by extracting the first two characters from the `DepartamentoRegistro` column and the first five characters from the `MunicipioRegistro` column, respectively. Finally, display the head of the DataFrame to verify the new columns.

## Extract CodDepartamento

### Subtask:
Create a new column named `CodDepartamento` by extracting the first two characters (the department code) from the `DepartamentoRegistro` column.

**Reasoning**:
To extract the first two characters from the 'DepartamentoRegistro' column and create a new column 'CodDepartamento', I will use the string slicing method on the column.
"""

df['CodDepartamento'] = df['DepartamentoRegistro'].str.slice(0, 2)
display(df[['DepartamentoRegistro', 'CodDepartamento']].head())

"""**Reasoning**:
To extract the first five characters from the 'MunicipioRegistro' column and create a new column 'CodMunicipio', I will use the string slicing method on the column.


"""

df['CodMunicipio'] = df['MunicipioRegistro'].str.slice(0, 5)
display(df[['MunicipioRegistro', 'CodMunicipio']].head())

"""**Reasoning**:
Both `CodDepartamento` and `CodMunicipio` columns have been created. Now, I will display the head of the DataFrame to verify these new columns as requested by the subtask.


"""

display(df[['DepartamentoRegistro', 'CodDepartamento', 'MunicipioRegistro', 'CodMunicipio']].head())

"""## Final Task

### Subtask:
Summarize the successful addition of the `CodDepartamento` and `CodMunicipio` columns to the DataFrame.

## Summary:

### Q&A
Yes, the addition of the `CodDepartamento` and `CodMunicipio` columns to the DataFrame was successful.

### Data Analysis Key Findings
*   A new column, `CodDepartamento`, was successfully created by extracting the first two characters from the `DepartamentoRegistro` column. For example, '05' was extracted from '05 - Antioquia'.
*   The `CodMunicipio` column was accurately generated by extracting the first five characters from the `MunicipioRegistro` column. For instance, '05001' was extracted from '05001 - Medellín'.
*   Both new columns were correctly added and populated in the DataFrame, as confirmed by displaying the head of the DataFrame.

### Insights or Next Steps
*   The newly created `CodDepartamento` and `CodMunicipio` columns provide standardized geographical identifiers that can be utilized for detailed regional analysis, filtering, or integration with other datasets requiring specific department and municipality codes.
*   Further data quality checks could be performed on these new code columns, such as verifying their uniqueness or checking against a master list of valid codes, if such a reference is available.
"""



"""## Extraer Mes y Día de 'FechaRegistro'

### Subtask:
Crear dos nuevas columnas, `Mes` y `Dia`, extrayendo la información correspondiente de la columna `FechaRegistro`.

**Reasoning**:
Para extraer el mes y el día de la columna `FechaRegistro`, que es de tipo `datetime`, utilizaré los atributos `.dt.month` y `.dt.day` de Pandas, respectivamente. Estas nuevas columnas se añadirán directamente al DataFrame `df`.
"""

df['Mes'] = df['FechaRegistro'].dt.month
df['Dia'] = df['FechaRegistro'].dt.day
display(df[['FechaRegistro', 'Mes', 'Dia']].head())

"""**Reasoning**:
Para exportar el DataFrame a un archivo CSV, utilizaré el método `df.to_csv()`. Especificaré `index=False` para evitar que el índice del DataFrame se escriba como una columna en el archivo CSV.
"""



"""## Exportar DataFrame Limpio a Excel (XLSX)

### Subtask:
Guardar el DataFrame `df` (ahora limpio de errores y con todas las columnas añadidas) en un archivo de Excel (`.xlsx`) para su posterior uso o descarga.

**Reasoning**:
Para exportar el DataFrame a un archivo de Excel, utilizaré el método `df.to_excel()`. Especificaré `index=False` para evitar que el índice del DataFrame se escriba como una columna en el archivo Excel. También se instalará la biblioteca `openpyxl` si no está presente, ya que es necesaria para escribir archivos `.xlsx`.

## Eliminar Filas con 'ERROR: #NAME?'

### Subtask:
Eliminar las filas que contengan el valor 'ERROR: #NAME?' en las columnas `DepartamentoRegistro` o `MunicipioRegistro`.

**Reasoning**:
Para eliminar las filas que contienen 'ERROR: #NAME?', primero se identificará cuántas filas tienen este valor en las columnas `DepartamentoRegistro` y `MunicipioRegistro`. Luego, se filtrará el DataFrame para excluir estas filas, actualizando el DataFrame `df`.
"""

# Contar filas con 'ERROR: #NAME?' antes de la eliminación
error_rows_departamento = df[df['DepartamentoRegistro'] == 'ERROR: #NAME?'].shape[0]
error_rows_municipio = df[df['MunicipioRegistro'] == 'ERROR: #NAME?'].shape[0]

print(f"Filas con 'ERROR: #NAME?' en DepartamentoRegistro antes de eliminar: {error_rows_departamento}")
print(f"Filas con 'ERROR: #NAME?' en MunicipioRegistro antes de eliminar: {error_rows_municipio}")

# Eliminar filas donde DepartamentoRegistro o MunicipioRegistro contienen 'ERROR: #NAME?'
df = df[~((df['DepartamentoRegistro'] == 'ERROR: #NAME?') | (df['MunicipioRegistro'] == 'ERROR: #NAME?'))]

print(f"Dimensiones del DataFrame después de eliminar errores: {df.shape}")
display(df.head())

# Instalar openpyxl si no está instalado
!pip install openpyxl

output_excel_path = 'datos_finales_RLCPD.xlsx'
df.to_excel(output_excel_path, index=False)
print(f"DataFrame exportado exitosamente a '{output_excel_path}'")